version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: atlasledger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: atlasledger
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: atlasledger-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-data:/data
